version: '3.5'
services:
  flexibee:
    image: flexibee:2025.1.1
    build:
      context: ./
      dockerfile: $PWD/Dockerfile
    volumes:
      - data:/var/lib/flexibee
      - log:/var/log
    environment:
      LANG: cs_CZ.UTF-8
      LANGUAGE: cs_CZ.UTF-8
      LC_ALL: cs_CZ.UTF-8

volumes:
  data:
  log:
